### ISSUE TITLE
No credits or about

### ISSUE THREAD

**Issue by Araraura** [Cofeiini/UndertaleSaveEditor#2]
I don't think there's a section of credits or an about that will lead into the github

**Comment by Cofeiini** [comment]
What exactly do you mean? Should there be an about and credits window in the application itself or on github page?

**Comment by Araraura** [comment]
> What exactly do you mean? Should there be an about and credits window in the application itself or on github page?

In the program itself

**Comment by Cofeiini** [comment]
I've added about option under Help menu in the latest release. The about window has a link to this project's github page and some credits.
