### ISSUE TITLE
No yellow names in credits option

### ISSUE THREAD

**Issue by Araraura** [Cofeiini/UndertaleSaveEditor#3]
There's no option to change the monster's name in the credits to yellow

**Comment by Cofeiini** [comment]
The "Spared" checkboxes (and maybe other widgets) in the Monsters Page control the flags that tell the game if the name is yellow in the credits.
I could add a tool window that allows making those names yellow.

**Comment by Cofeiini** [comment]
I've added a feature to change names in the credits to yellow. It can be found under Tools menu in the latest release.
